routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Route::get('/patientregistration','PatientregistrationController@index');
Route::get('/patientregistration/create','PatientregistrationController@create');
Route::post('/patientregistration/create','PatientregistrationController@store');
Route:: get('/patientregistration/edit/{id}','PatientregistrationController@edit');
Route:: post('/patientregistration/edit/{id}','PatientregistrationController@update');
Route:: get('/patientregistration/delete/{id}','PatientregistrationController@destroy');

Route::post('/getPatient', 'PatientregistrationController@getById');
Route::get('/home', 'PatientregistrationController@getPatient');
Route::get('/getPatient', 'PatientregistrationController@getPatient');
Route::post('/newOpdRegistration', 'PatientregistrationController@opdRegistration');

Auth::routes();



Route::post('/rxentry', 'RxController@store');
Route::post('/rxentry/edit/{id}', 'RxController@update');
Route::delete('/rxentry/delete/{id}', 'RxController@destroy');


Route::post('/oesubmit', 'OnExaminationController@store');
Route::post('/oeexamination', 'OnExaminationController@oeexaminationn');
Route::delete('/o_e/delete/{id}', 'OnExaminationController@destroy');
Route::post('/o_e/edit/{id}', 'OnExaminationController@update');


Route::post('/pathology', 'PathologyController@store');

Route::get('/pathology/print/{patient_id}', 'HomeController@printReport');

Route::get('/departments','DepartmentController@index');
Route::get('/department/create', 'DepartmentController@create');
Route::post('/department/create', 'DepartmentController@store');
Route::get('/department/edit/{id}', 'DepartmentController@edit')->name('department.edit');
Route::post('/department/edit/{id}', 'DepartmentController@update')->name('department.update');
Route::delete('/department/destroy/{id}', 'DepartmentController@destroy')->name('department.delete');

Route::get('/test-category','TestCategoryController@index');
Route::get('/test-category/create', 'TestCategoryController@create');
Route::post('/test-category/create', 'TestCategoryController@store');
Route::get('/test-category/edit/{id}', 'TestCategoryController@edit')->name('test-category.edit');
Route::post('/test-category/edit/{id}', 'TestCategoryController@update')->name('test-category.update');
Route::delete('/test-category/destroy/{id}', 'TestCategoryController@destroy')->name('test-category.delete');

Route::get('/tests','TestController@index');
Route::get('/test/create', 'TestController@create');
Route::post('/test/create', 'TestController@store');
Route::get('/test/edit/{id}', 'TestController@edit')->name('test.edit');
Route::post('/test/edit/{id}', 'TestController@update')->name('test.update');
Route::delete('/test/destroy/{id}', 'TestController@destroy')->name('test.delete');


Route::get('/user-management', 'PatientregistrationController@userManagement');

Route::resource('doctors', 'DoctorsController');


Route::post('/cosubmit', 'ChiefComplaintsController@store');
Route::delete('/c_o/delete/{id}', 'ChiefComplaintsController@destroy');
Route::post('/c_o/edit/{id}', 'ChiefComplaintsController@update');

Route::post('/followup', 'FollowUpController@store');
Route::post('/historyIllness', 'HistoryIllnessController@store');
Route::delete('/historyIllness/delete/{id}', 'HistoryIllnessController@destroy');
Route::post('/history/edit/{id}', 'HistoryIllnessController@update');


Route::post('/investigation', 'InvestigationController@store');
Route::delete('/investigation/delete/{id}', 'InvestigationController@destroy');
Route::post('/investigation/edit/{id}', 'InvestigationController@update');

Route::get('/roleChange/{user_id}/{role_id}', 'UserController@assign');
Route::delete('/user/delete/{id}', 'UserController@destroy');

Route::get('/registered', 'HomeController@registered');



Route::get('/prescription/print/{patient_id}', 'HomeController@printPescription');
Route::get('/exportPdf', 'HomeController@exportPdf');
Route::get('/receipt/print/{patient_id}', 'HomeController@printReceipt');


Route::get('/overallReport', 'ReportGenerationController@overallReport');

// Route::get('/print', function(){
// 	return view('template.printTemplate');
// });

app/Doctor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
    protected $fillable = [
    	'doctor_name', 'specialization', 'dept_id'
    ];
}

app/Http/Controllers/DoctorsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Doctor;
use App\Department;
use App\Http\Requests\createDoctorRequest;
use App\Http\Requests\updateDoctorRequest;


class DoctorsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $doctors = Doctor::all();
        $departments = Department::all();
        return view('doctor.display', compact('doctors', 'departments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        return view('doctor.create', compact('departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(createDoctorRequest $request)
    {
        $input = $request->all();
        $doctor = Doctor::create($input);
        // dd($doctor);
        return redirect('/doctors')->with('success', $doctor->name . ' is created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $doctor = Doctor::findOrFail($id);
        $departments = Department::all();
        return view('doctor.edit', compact('doctor', 'departments'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(updateDoctorRequest $request, $id)
    {
        $doctor = Doctor::findOrFail($id);
        $input = $request->all();
        // dd('Here');
        $doctor->update($input);
        return redirect('/doctors')->with('success', $doctor->name . ' is updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $doctor = Doctor::findOrFail($id);
        $doctor->delete();
        return redirect('/doctors');
    }
}

resources/views/doctor/create.blade.php
@extends('layouts.app')

@section('content')

<div class="doctors">
	<form action="{{ route('doctors.store') }}" method="POST">
		@csrf

		<div class="row">
			<div class="col-sm-6">
				<div class="form-group">
					<label for="name">Name</label>
					<input type="text" class="form-control" name="doctor_name">
				</div>
				<div class="form-group">
					<label for="specialization">Specialization</label>
					<input type="text" class="form-control" name="specialization">
				</div>
			</div>
			<div class="col-sm-6">
				<div class="form-group">
					<label for="dept_id">Department</label>
					<select name="dept_id" id="" class="form-control">
						<option value="">Select Department</option>
						@foreach($departments as $department)
							<option value="{{ $department->id }}">{{ $department->name }}</option>
						@endforeach
					</select>
				</div>
				<div class="form-group">
					<button class="btn btn-primary btn-block submit-doc" type="submit">Submit</button>
				</div>
			</div>
		</div>	
	</form>
</div>

@endsection

resources/views/doctor/display.blade.php
@extends('layouts.app')

@section('content')
<div class="doctors">
	<div class="c_o_content">
		<div class="header-text">
			<h3>
				Doctor's List
			</h3>
			<a href="{{ route('doctors.create')}}" class="link-create"><i class="fa fa-plus"></i></a>
		</div>
	</div>
	<table class="table table-hover">
		<thead>
			<th>S.N</th>
			<th>Name</th>
			<th>Specialization</th>
			<th>Department</th>
			<th>Action</th>
		</thead>
		<tbody>
			@foreach($doctors as $doctor)
			<tr>
				<td>{{ $loop->iteration }}</td>
				<td>{{ $doctor->doctor_name }}</td>
				<td>{{ $doctor->specialization }}</td>
				<td>
					@foreach($departments as $department)
					@if($doctor->dept_id == $department->id)
						{{ $department->name }}
					@endif
					@endforeach
				</td>
				<td>
					<a href="{{ route('doctors.edit', [$doctor->id]) }}" class="btn btn-primary btn-block">Edit</a>
					<form action="{{ route('doctors.destroy', [$doctor->id]) }}" method="POST">
						@csrf
						@method('delete')
						<button class="btn btn-danger btn-block" onclick="confirmation(event)">Delete</button>
					</form>
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>
</div>
@endsection
@section('scripts')
<script src="{{ asset('js/sys.js') }}"></script>

@endsection

resources/views/doctor/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="doctors">
	<form action="{{ route('doctors.update', $doctor->id) }}" method="POST">
		@csrf
		@method('PUT')
		<div class="row">
			<div class="col-sm-6">
				<div class="form-group">
					<label for="doctor_name">Name</label>
					<input type="text" class="form-control" name="doctor_name" value="{{ $doctor->doctor_name }}">
				</div>
				<div class="form-group">
					<label for="specialization">Specialization</label>
					<input type="text" class="form-control" name="specialization" value="{{ $doctor->specialization }}">
				</div>
			</div>
			<div class="col-sm-6">
				<div class="form-group">
					<label for="dept_id">Department</label>
					<select name="dept_id" id="" class="form-control">
						<option value="">Select Department</option>
						@foreach($departments as $department)
							<option value="{{ $department->id }}" <?php if($department->id == $doctor->dept_id) echo 'selected' ;?>>{{ $department->name }}</option>
						@endforeach
					</select>
				</div>
				<div class="form-group">
					<button class="btn btn-primary btn-block submit-doc" type="submit">Submit</button>
				</div>
			</div>
		</div>	
	</form>
</div>

@endsection